"""OSCAL Component Definition export for CMMC controls."""
from __future__ import annotations
import json
import uuid
from datetime import datetime, timezone
from typing import Optional
from .mapper import load_controls, get_controls_by_level


def generate_oscal_component_definition(
    level: int = 2,
    system_name: str = "AWS Cloud Environment",
    organization: str = "My Organization",
) -> dict:
    """
    Generate an OSCAL 1.1.x Component Definition document mapping
    CMMC controls to AWS service implementations.
    """
    controls = get_controls_by_level(level)
    now = datetime.now(timezone.utc).isoformat()

    # Build implemented requirements
    implemented_requirements = []
    for control in controls:
        statements = []
        for i, service in enumerate(control.get("aws_services", [])):
            statements.append({
                "statement-id": f"{control['id']}-stmt-{i+1}",
                "uuid": str(uuid.uuid4()),
                "description": f"Implemented using {service}.",
                "remarks": f"AWS Config rules: {', '.join(control.get('aws_config_rules', ['N/A']))}",
            })

        implemented_requirements.append({
            "uuid": str(uuid.uuid4()),
            "control-id": control["id"].lower().replace(".", "-"),
            "description": control["practice"],
            "remarks": f"Domain: {control['domain']} | NIST Mappings: {', '.join(control.get('nist_mapping', []))}",
            "statements": statements,
        })

    oscal_doc = {
        "component-definition": {
            "uuid": str(uuid.uuid4()),
            "metadata": {
                "title": f"CMMC Level {level} AWS Component Definition",
                "last-modified": now,
                "version": "1.0.0",
                "oscal-version": "1.1.2",
                "remarks": f"Generated by cmmc-control-mapper for {organization}",
            },
            "components": [
                {
                    "uuid": str(uuid.uuid4()),
                    "type": "software",
                    "title": system_name,
                    "description": f"AWS cloud environment implementing CMMC Level {level} controls.",
                    "control-implementations": [
                        {
                            "uuid": str(uuid.uuid4()),
                            "source": "https://dodcio.defense.gov/CMMC/",
                            "description": f"CMMC 2.0 Level {level} control implementations mapped to AWS services.",
                            "implemented-requirements": implemented_requirements,
                        }
                    ],
                }
            ],
        }
    }
    return oscal_doc


def export_oscal_json(
    output_path: str,
    level: int = 2,
    system_name: str = "AWS Cloud Environment",
    organization: str = "My Organization",
) -> str:
    """Export OSCAL Component Definition to a JSON file."""
    doc = generate_oscal_component_definition(level, system_name, organization)
    with open(output_path, "w") as f:
        json.dump(doc, f, indent=2)
    return output_path
